dev/playerqueenview
Long2511/SleepingQueen pull request #14
Opened 2024-12-28 21:07 UTC by Smile030504

2024-12-28 21:08 UTC, Smile030504 commented
![image](https://github.com/user-attachments/assets/f7eb32e5-f2eb-4a9d-a68d-40c1b00d59af)

2024-12-30 00:34 UTC, Long2511 requested changes

2024-12-30 00:34 UTC, Long2511 commented on src/main/java/com/ouroboros/sleepingqueen/PreGameScreenController.java
Why Delete a function?

2024-12-30 00:34 UTC, Long2511 commented on src/main/resources/com/ouroboros/sleepingqueen/view/board-view.fxml
> -<AnchorPane prefHeight="720" prefWidth="1280" stylesheets="@../css/styles.css" xmlns="http://javafx.com/javafx/23.0.1" xmlns:fx="http://javafx.com/fxml/1" fx:controller="com.ouroboros.sleepingqueen.B
Why change the dimension and delete the styles.css

2024-12-30 00:34 UTC, Long2511 commented on src/main/resources/com/ouroboros/sleepingqueen/view/rule-screen.fxml
No images in PR for review

2024-12-30 01:27 UTC, Smile030504 commented
![image](https://github.com/user-attachments/assets/b9945b67-b90c-488f-b733-d176dc06bdf9)

2024-12-31 15:29 UTC, xiinthanh approved these changes

2024-12-31 15:30 UTC, Long2511 approved these changes

2024-12-31 15:30 UTC, Long2511 commented on src/main/resources/com/ouroboros/sleepingqueen/view/player-score-and-menu.fxml
> +            <Button mnemonicParsing="false" text="menu">
Should be "Menu" not "menu"

2024-12-31 15:30 UTC, xiinthanh approved these changes

2024-12-31 15:33 UTC, Long2511 approved these changes

2024-12-31 15:35 UTC, merged